language: python
python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r test_requirements.txt

script:
  - python runtests.py
